# Serenity Configuration
serenity.browser.height=1080
serenity.browser.width=1920
serenity.restart.browser.for.each=scenario
serenity.driver.capabilities=browserName:chrome;chromeOptions.args:--headless,--no-sandbox,--disable-dev-shm-usage

# Cucumber Configuration
cucumber.publish.quiet=true

# Webdriver Manager
webdriver.chrome.driver.version=latest
webdriver.firefox.driver.version=latest

# Logging
serenity.logging=INFO

# Reports
serenity.report.show.pie.charts=true
serenity.report.show.step.details=true
serenity.report.show.releases=true
